name: FPC Echo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-20.04
    env:
      GOPATH: ${{ github.workspace }}
      GOFLAGS: -mod=mod
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/hyperledger-labs/fabric-smart-client
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/hyperledger-labs/fabric-smart-client

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Checks
      run: make install-tools checks

    - name: Integration Tests
      run: make integration-tests-fpc-echo
